# CI du microservice notifications
backend:microservice:notifications:
  stage: packages
  needs:
    - check-nodejs-version
  variables:
    NODE_VERSION: $NODE_VERSION
  trigger:
    include: ${BACKEND_PATH}/microservices/notifications/.gitlab-ci.yml
    strategy: depend
  rules:
    # On ne d√©clenche ce job que lorsqu'il y a eu du changement au niveau de backend/microservices/map
    - if: '$CI_COMMIT_BRANCH == "develop-sied"'
      changes:
        - ${BACKEND_PATH}/microservices/notifications/**/*
