# CI du microservice static-pages
backend:microservice:static-pages:
  stage: packages
  needs:
    - check-nodejs-version
  variables:
    NODE_VERSION: $NODE_VERSION
  trigger:
    include: ${BACKEND_PATH}/microservices/static-pages/.gitlab-ci.yml
    strategy: depend
  rules:
    # On ne d√©clenche ce job que lorsqu'il y a eu du changement au niveau de backend/microservices/static-pages
    - if: '$CI_COMMIT_BRANCH == "develop-sied"'
      changes:
        - ${BACKEND_PATH}/microservices/static-pages/**/*
