version: 1
directus: 9.19.2
collections:
  - collection: info
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: info
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: sort
      translations: null
      unarchive_value: draft
    schema:
      comment: null
      name: info
      schema: public
fields:
  - collection: info
    field: content
    meta:
      collection: info
      conditions: null
      display: null
      display_options: null
      field: content
      group: null
      hidden: false
      interface: input-multiline
      note: null
      options: null
      readonly: false
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: text
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: content
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: info
    type: text
  - collection: info
    field: date_created
    meta:
      collection: info
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 2
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: info
    type: timestamp
  - collection: info
    field: date_updated
    meta:
      collection: info
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 3
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: info
    type: timestamp
  - collection: info
    field: id
    meta:
      collection: info
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: nextval('info_id_seq'::regclass)
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: info
    type: integer
  - collection: info
    field: link
    meta:
      collection: info
      conditions: null
      display: null
      display_options: null
      field: link
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: link
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: info
    type: string
  - collection: info
    field: sort
    meta:
      collection: info
      conditions: null
      display: null
      display_options: null
      field: sort
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 7
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: sort
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: info
    type: integer
  - collection: info
    field: ssoService
    meta:
      collection: info
      conditions: null
      display: null
      display_options: null
      field: ssoService
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 6
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: ssoService
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: info
    type: string
  - collection: info
    field: status
    meta:
      collection: info
      conditions: null
      display: labels
      display_options:
        choices:
          - text: $t:published
            value: published
            foreground: '#FFFFFF'
            background: var(--primary)
          - text: $t:draft
            value: draft
            foreground: '#18222F'
            background: '#D3DAE4'
          - text: $t:archived
            value: archived
            foreground: '#FFFFFF'
            background: var(--warning)
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: $t:published
            value: published
          - text: $t:draft
            value: draft
          - text: $t:archived
            value: archived
      readonly: false
      required: false
      sort: 8
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: draft
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: status
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: info
    type: string
  - collection: info
    field: title
    meta:
      collection: info
      conditions: null
      display: null
      display_options: null
      field: title
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 9
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: title
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: info
    type: string
  - collection: info
    field: user_created
    meta:
      collection: info
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 10
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: info
    type: uuid
  - collection: info
    field: user_updated
    meta:
      collection: info
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 11
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_updated
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: info
    type: uuid
relations:
  - collection: info
    field: user_created
    meta:
      junction_field: null
      many_collection: info
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: info_user_created_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: info
  - collection: info
    field: user_updated
    meta:
      junction_field: null
      many_collection: info
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_updated
      constraint_name: info_user_updated_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: info
