# CI du microservice contact-us

.contact-us_service_variables:
  variables:
    # Chemin vers le répertoire du service depuis le backend
    SERVICE_FOLDER: "microservices/contact-us"
    # Nom qui sera donné à l'image Docker du service
    SERVICE_IMAGE_NAME: "backend/multi-contact-us"
    # Nom du service pour le déclenchement manuel dans GitLab
    CI_SERVICE_NAME: "contact-us"

include:
  - local: '${CI_PROJECT_DIR}/ci-config/example/backend/templates-ci.yml'

build-service-contact-us:
  extends:
    - .contact-us_service_variables
    - .template_build_microservice
    - .microservice_rules_template
  stage: build-package

deploy-service-contact-us:
  extends:
    - .contact-us_service_variables
    - .template_docker_deploy_microservice
    - .microservice_rules_template
  stage: build-deploy-docker
  needs:
    - job: build-service-contact-us
      artifacts: true
