# CI du microservice important-news

.important-news_service_variables:
  variables:
    # Chemin vers le répertoire du service depuis le backend
    SERVICE_FOLDER: "microservices/important-news"
    # Nom qui sera donné à l'image Docker du service
    SERVICE_IMAGE_NAME: "backend/multi-important-news"
    # Nom du service pour le déclenchement manuel dans GitLab
    CI_SERVICE_NAME: "important-news"

include:
  - local: '${CI_PROJECT_DIR}/ci-config/example/backend/templates-ci.yml'

build-service-important-news:
  extends:
    - .important-news_service_variables
    - .template_build_microservice
    - .microservice_rules_template
  stage: build-package

deploy-service-important-news:
  extends:
    - .important-news_service_variables
    - .template_docker_deploy_microservice
    - .microservice_rules_template
  stage: build-deploy-docker
  needs:
    - job: build-service-important-news
      artifacts: true
