# CI du microservice mail-calendar

.mail-calendar_service_variables:
  variables:
    # Chemin vers le répertoire du service depuis le backend
    SERVICE_FOLDER: "microservices/mail-calendar"
    # Nom qui sera donné à l'image Docker du service
    SERVICE_IMAGE_NAME: "backend/multi-mail-calendar"
    # Nom du service pour le déclenchement manuel dans GitLab
    CI_SERVICE_NAME: "mail-calendar"

include:
  - local: '${CI_PROJECT_DIR}/ci-config/example/backend/templates-ci.yml'

build-service-mail-calendar:
  extends:
    - .mail-calendar_service_variables
    - .template_build_microservice
    - .microservice_rules_template
  stage: build-package

deploy-service-mail-calendar:
  extends:
    - .mail-calendar_service_variables
    - .template_docker_deploy_microservice
    - .microservice_rules_template
  stage: build-deploy-docker
  needs:
    - job: build-service-mail-calendar
      artifacts: true
