# CI du microservice restaurants

.restaurants_service_variables:
  variables:
    # Chemin vers le répertoire du service depuis le backend
    SERVICE_FOLDER: "microservices/restaurants"
    # Nom qui sera donné à l'image Docker du service
    SERVICE_IMAGE_NAME: "backend/multi-restaurants"
    # Nom du service pour le déclenchement manuel dans GitLab
    CI_SERVICE_NAME: "restaurants"

include:
  - local: '${CI_PROJECT_DIR}/ci-config/example/backend/templates-ci.yml'

build-service-restaurants:
  extends:
    - .restaurants_service_variables
    - .template_build_microservice
    - .microservice_rules_template
  stage: build-package

deploy-service-restaurants:
  extends:
    - .restaurants_service_variables
    - .template_docker_deploy_microservice
    - .microservice_rules_template
  stage: build-deploy-docker
  needs:
    - job: build-service-restaurants
      artifacts: true
