# CI du microservice schedule

.schedule_service_variables:
  variables:
    # Chemin vers le répertoire du service depuis le backend
    SERVICE_FOLDER: "microservices/schedule"
    # Nom qui sera donné à l'image Docker du service
    SERVICE_IMAGE_NAME: "backend/multi-schedule"
    # Nom du service pour le déclenchement manuel dans GitLab
    CI_SERVICE_NAME: "schedule"

include:
  - local: '${CI_PROJECT_DIR}/ci-config/example/backend/templates-ci.yml'

build-service-schedule:
  extends:
    - .schedule_service_variables
    - .template_build_microservice
    - .microservice_rules_template
  stage: build-package

deploy-service-schedule:
  extends:
    - .schedule_service_variables
    - .template_docker_deploy_microservice
    - .microservice_rules_template
  stage: build-deploy-docker
  needs:
    - job: build-service-schedule
      artifacts: true
