# CI du microservice social-network

.social-network_service_variables:
  variables:
    # Chemin vers le répertoire du service depuis le backend
    SERVICE_FOLDER: "microservices/social-network"
    # Nom qui sera donné à l'image Docker du service
    SERVICE_IMAGE_NAME: "backend/multi-social-network"
    # Nom du service pour le déclenchement manuel dans GitLab
    CI_SERVICE_NAME: "social-network"

include:
  - local: '${CI_PROJECT_DIR}/ci-config/backend/templates-ci.yml'

build-service-social-network:
  extends:
    - .social-network_service_variables
    - .template_build_microservice
    - .microservice_rules_template
  stage: build-package

deploy-service-social-network:
  extends:
    - .social-network_service_variables
    - .template_docker_deploy_microservice
    - .microservice_rules_template
  stage: build-deploy-docker
  needs:
    - job: build-service-social-network
      artifacts: true
