# CI de la PWA de dev

.pwa_dev_variables:
  variables:
    # Nom de la variable de conf pour le build Angular
    PWA_ENV_CONFIG_NAME: "pwa-development"
    # Nom du fichier firebase à inclure à l'environnement
    FIREBASE_FILENAME: "firebase-environment.pwa-development.json"
    # Nom qui sera donné à l'image Docker du service
    PWA_IMAGE_NAME: "frontend/multi-pwa"
    # Nom de la PWA pour le déclenchement manuel dans GitLab
    PWA_CI_NAME: "pwa-dev"
    # Nom de la branche correspondant à l'app de dev
    PWA_BRANCH_NAME: "develop"

include:
  - local: '${CI_PROJECT_DIR}/ci-config/frontend/templates-ci.yml'

build-pwa-dev:
  extends:
    - .pwa_dev_variables
    - .template_build_pwa
    - .pwa_rules_template
  stage: build-package

deploy-pwa-dev:
  extends:
    - .pwa_dev_variables
    - .template_docker_deploy_pwa
    - .pwa_rules_template
  stage: build-deploy-docker
  needs:
    - job: build-pwa-dev
      artifacts: true
